export const defaulltProps = {
  columns: () => [{ label: '菜单名称', prop: 'id', align: 'center' }],
  tableSize: 'mini',
  mode: 'normal',
  defaultPanel: () => ['add', 'edit', 'delete'],
  pageAlign: 'right',
  pageSize: 20,
  pageIndex: 1,
  showSettingToolbar: true,
  showPage: true,
  highlightCurrentRow: false,
  lazy: false,
  height: '63vh',
  border: true,
  showSummary: false,
  stripe: true,
  showSettingTool: true,
  showPanelTool: true,
  responseName: () => 'list',
  isPrivate: false
}
